export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REQUST_TASKS = 'REQUST_TASKS';
export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const RECEIVE_TASKS_ERROR = 'FETCH_TASKS_ERROR';

export const RECEIVE_TASK_DETAIL = 'RECEIVE_TASK_DETAIL';
export const RECEIVE_TASK_DETAIL_ERROR = 'RECEIVE_TASK_DETAIL_ERROR';
export const HIDE_DETAIL_WINDOW = 'HIDE_DETAIL_WINDOW';
export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';
export const RESET_TASKS = 'RESET_TASKS';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';

// list 相关
export const FETCH_LISTS = 'FETCH_LISTS';
export const FETCH_LISTS_ERROR = 'FETCH_LISTS_ERROR';
export const ADD_LIST = 'ADD_LIST';
export const ADD_LIST_ERROR = 'ADD_LIST_ERROR';
export const EDIT_LIST = 'EDIT_LIST';
export const DELETE_LIST = 'DELETE_LIST';
export const DELETE_LIST_ERROR = 'DELETE_LIST_ERROR';

export const UPDATE_LIST = 'UPDATE_LIST';

export const FETCHING = 'FETCHING';